# IP Forwarding (for Docker)
net.ipv4.ip_forward = 1

# Disable IPv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.wlan0.disable_ipv6 = 1

# TCP SYN Cookie Protection
net.ipv4.tcp_syncookies = 1

# Disable Source Routing
net.ipv4.conf.all.accept_source_route = 0

# Disable ICMP Redirects
net.ipv4.conf.all.accept_redirects = 0

# Source Address Verification (Anti IP Spoofing)
net.ipv4.conf.all.rp_filter = 1

# Ignore ICMP requests
net.ipv4.icmp_echo_ignore_all = 1

# Ignore broadcast ICMP requests
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Bad Error Message Protection
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Enable Logging of Martian packets
net.ipv4.conf.all.log_martians = 1

# Swappiness (lower = less swap usage)
vm.swappiness = 15
