 # Artix
 [system]
 Include = /etc/pacman.d/mirrorlist

 [world]
 Include = /etc/pacman.d/mirrorlist

 [galaxy]
 Include = /etc/pacman.d/mirrorlist

 [lib32]
 Include = /etc/pacman.d/mirrorlist

 # Arch
 [extra]
 Include = /etc/pacman.d/mirrorlist-arch

# [multilib]
# Include = /etc/pacman.d/mirrorlist-arch
[options]
IgnorePkg = ffmpeg
#IgnorePkg = libreoffice-still boost nodejs kitty llvm-libs kdenlive python mesa boost-libs sudo linux icu harfbuzz gsfonts
#IgnorePkg = libreoffice-still boost nodejs kitty llvm-libs kdenlive python mes
Architecture = auto
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
